version: '3'
volumes:
  postgres-data:

services:
  postgresql:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=master_db
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    restart: always


#  formify-api:
#    container_name: 'formify-api'
#    build:
#      context: .
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://formify_postgresql_1:5432/master_db
#    ports:
#      - '8080:8080'
#    volumes:
#      - /opt/server-img/:/server-img/
#    depends_on:
#      - postgresql